// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbd33T5b-ymyh-9RSz-RSBiO8qR7298iY',
    appId: '1:981548234484:web:0a30bbc3818ae8daf010a1',
    messagingSenderId: '981548234484',
    projectId: 'sohila-1efc2',
    authDomain: 'sohila-1efc2.firebaseapp.com',
    databaseURL: 'https://sohila-1efc2-default-rtdb.firebaseio.com',
    storageBucket: 'sohila-1efc2.firebasestorage.app',
    measurementId: 'G-B0D0D7K8T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoaF7ufPDlXeXLaiiwBBnz0IdKByDKw8s',
    appId: '1:981548234484:android:8fb15d8a5852cd0ef010a1',
    messagingSenderId: '981548234484',
    projectId: 'sohila-1efc2',
    databaseURL: 'https://sohila-1efc2-default-rtdb.firebaseio.com',
    storageBucket: 'sohila-1efc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsD6tj1lArHRkDbALfPL-qi72mPi1XZEA',
    appId: '1:981548234484:ios:e0384a5ff67da52cf010a1',
    messagingSenderId: '981548234484',
    projectId: 'sohila-1efc2',
    databaseURL: 'https://sohila-1efc2-default-rtdb.firebaseio.com',
    storageBucket: 'sohila-1efc2.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsD6tj1lArHRkDbALfPL-qi72mPi1XZEA',
    appId: '1:981548234484:ios:e0384a5ff67da52cf010a1',
    messagingSenderId: '981548234484',
    projectId: 'sohila-1efc2',
    databaseURL: 'https://sohila-1efc2-default-rtdb.firebaseio.com',
    storageBucket: 'sohila-1efc2.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbd33T5b-ymyh-9RSz-RSBiO8qR7298iY',
    appId: '1:981548234484:web:bda5abb4c87e4fdbf010a1',
    messagingSenderId: '981548234484',
    projectId: 'sohila-1efc2',
    authDomain: 'sohila-1efc2.firebaseapp.com',
    databaseURL: 'https://sohila-1efc2-default-rtdb.firebaseio.com',
    storageBucket: 'sohila-1efc2.firebasestorage.app',
    measurementId: 'G-8YR2YZM0GC',
  );

}